# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.

name: PowerShell Formula
on:
  push:
    branches:
      - master
  pull_request:
    paths-ignore:
      - 'Formula/powershell-preview.rb'
  #schedule:
    # At 16:00 UTC on every day-of-week from Monday through Friday.
  #  - cron:  '0 16 * * 1-5'
defaults:
  run:
    shell: pwsh
env:
  FORMULA_PATH: ./Formula/powershell.rb
  UPDATE_SCRIPT_PATH: ./scripts/update_formula.ps1
  FORMULA_NAME: powershell
jobs:
  homebrew-formula:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      # See https://brew.sh
      - name: Install homebrew prerequisite
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
      - name: brew uninstall cask
        shell: bash
        run: |
          brew cask uninstall $FORMULA_NAME || true
      - name: brew install (Verify install of formula)
        shell: bash
        run: |
          brew install --verbose --build-from-source $FORMULA_PATH
      # See https://docs.brew.sh/Formula-Cookbook#audit-the-formula
      - name: brew audit (Audit formula)
        run: |
          brew audit --strict --online --display-filename --display-cop-names $env:FORMULA_PATH
      # See https://docs.brew.sh/Formula-Cookbook#add-a-test-to-the-formula
      - name: brew test (Verify tests in formula)
        run: |
          brew test $env:FORMULA_PATH
      # - name: (scheduled-auto-release) Commit & Push changes
      #   if: github.event_name == 'schedule'
      #   run: |
      #     git diff
      #     if git diff --exit-code $FORMULA_PATH
      #     then
      #       echo "Nothing to do."
      #     else
      #       echo "Pushing changes."
      #       git config --local user.email "action@github.com"
      #       git config --local user.name "GitHub Action"
      #       git add $FORMULA_PATH
      #       if [ -z "$NEW_FORMULA_VERSION" ]
      #       then
      #             git commit -m "Update powershell formula version"
      #       else
      #             git commit -m "Update powershell formula to version $NEW_FORMULA_VERSION"
      #       fi
      #       git push "https://${GITHUB_ACTOR}:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git" HEAD:master
      #     fi
